# -*- coding: utf-8 -*-
"""Geocoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zaJy0LB_JDAFFgBnmY9dQdd-94ase-rn
"""

pip install googlemaps

import pandas as pd
import googlemaps

# 🔹 Load Excel file
file_path = "geocoding.xlsx"  # Change this to your actual file
sheet_name = "Top 18 customers (2)"  # Change if your sheet name is different

# 🔹 Read Excel
df = pd.read_excel(file_path, sheet_name=sheet_name)

# 🔹 Ensure column name is correct
address_column = "Updated Full Address"  # Change if your column name is different

# 🔹 Initialize Google Maps API client
GOOGLE_API_KEY = "Hidden for Privacy"  # Replace with your actual API key
gmaps = googlemaps.Client(key=GOOGLE_API_KEY)

# 🔹 Function to get coordinates
def get_coordinates(address):
    try:
        geocode_result = gmaps.geocode(address)
        if geocode_result:
            location = geocode_result[0]['geometry']['location']
            return pd.Series([location['lat'], location['lng']])
        else:
            return pd.Series([None, None])  # Address not found
    except Exception as e:
        print(f"Error with address {address}: {e}")
        return pd.Series([None, None])  # Handle errors

# 🔹 Apply geocoding function to addresses
df[['Latitude', 'Longitude']] = df[address_column].apply(get_coordinates)

# 🔹 Save results back to Excel
output_file = "geocoded_addresses_google.xlsx"
df.to_excel(output_file, index=False)

print(f"✅ Geocoded data saved to {output_file}")